package com.jacpower.groupsApp.enums;

public enum RequestTypes {
    CREATE_USER, GET_ROLE, CREATE_GROUP, GET_USER_ID, GET_GROUP_DETAILS, UPDATE_GROUP, CREATE_MEMBER, GET_GROUP_ID,
    GET_GROUP_MEMBERS, GET_MEMBER_BY_ID, UPDATE_MEMBER_DETAILS, ACTIVATE_MEMBER, DEACTIVATE_MEMBER, ADD_MEETING,
    GET_GROUP_MEETINGS, CLOSE_MEETING, ADD_ATTENDANCE, GET_ATTENDANCE_DETAILS
}
