package com.jacpower.groupsApp.enums;

public enum RequestTypes {
    CREATE_USER, GET_ROLE, CREATE_GROUP, GET_USER_ID, GET_GROUP_DETAILS, UPDATE_GROUP, CREATE_MEMBER, GET_GROUP_ID,
    GET_GROUP_MEMBERS, GET_MEMBER_BY_ID, UPDATE_MEMBER_DETAILS, ACTIVATE_MEMBER, DEACTIVATE_MEMBER, ADD_MEETING,
    GET_GROUP_MEETINGS, CLOSE_MEETING, ADD_ATTENDANCE, GET_ATTENDANCE_DETAILS, DOES_ACCOUNT_EXIST, CREATE_ACCOUNT,
    GET_ACCOUNT_DETAILS, ADD_UPDATE_ATTENDANCE, DEDUCT_UPDATE_ATTENDANCE, GET_INVENTORY_DETAILS, DEPOSIT_TO_ACCOUNT,
    WITHDRAW_FROM_ACCOUNT, REQUEST_LOAN, APPROVE_LOAN, GET_LOANS, DENY_LOAN, REPAY_LOAN, ADD_UPDATE_LOTTERY,
    GET_WINNER, APPROVE_LOTTERY, GET_LOTTERY_SUMMARY, UPDATE_USERNAME_PASSWORD, DEACTIVATE_GROUP, CREATE_ADMIN, GET_ALL_GROUPS
}
